RegistrationApp/urls.py
from django.conf.urls import url
from .views import registrationIndex

urlpatterns = [
    url(r'^$', registrationIndex, name='registrationIndex'),
]

TP_PPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from LogoutApp import views as logout_views
from ProgramApp import views as program_views
from RegistrationApp import views as regis_views

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/news/')),
    url(r'^admin/', admin.site.urls),
    url(r'^program/', include(('ProgramApp.urls', 'ProgramApp'), namespace='donasi_kuy')),
    url(r'^news/', include(('BeritaApp.urls', 'BeritaApp'), namespace='news')),
    url(r'^registration/', include(('RegistrationApp.urls', 'RegistrationApp'), namespace='registration')),
    url(r'^donationList/', include(('donationListApp.urls', 'donationListApp'), namespace='donationList')),
    url(r'^logout/', logout_views.logout, name='logoutapp'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^validate/', program_views.validate, name='validate'),
    url(r'^login/', regis_views.loginIndex, name='login'),
    url(r'^about/', include(('AboutApp.urls', 'AboutApp'), namespace='about')),
]

RegistrationApp/models.py
from django.db import models

# Create your models here.


class user_registration(models.Model):
    nama = models.CharField(max_length=255)
    tanggal_lahir = models.DateField()
    email = models.EmailField()
    password = models.CharField(max_length=50)

ProgramApp/forms.py
from django import forms
from .models import program_update


class MyModelChoiceField(forms.ModelChoiceField):
    widget = forms.Select(attrs={'class': 'form-control'})
    empty_label = "Pilih program donasi"

    def label_from_instance(self, obj):
        return obj.judul


class program_registration_form(forms.Form):
    program = MyModelChoiceField(program_update.objects.all())
    jumlah_uang = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control shadow-box-form', 'placeholder': 'Masukkan jumlah uang !'}))
    tampilkan = forms.BooleanField(required=False, initial=True, widget=forms.CheckboxInput())

RegistrationApp/forms.py
from django import forms
from .models import user_registration

class tanggalWidget(forms.DateInput):
    input_type = 'date'

class passwordWidget(forms.PasswordInput):
    input_type = 'password'

class user_registration_form(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(user_registration_form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = user_registration
        fields = [
            'nama',
            'tanggal_lahir',
            'email',
            'password',
        ]
        widgets = {
            'tanggal_lahir' : tanggalWidget(),
            'password' : passwordWidget(),
        }

class login_form(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(login_form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = user_registration
        fields = [
            'nama',
            'password',
        ]
        widgets = {
            'password' : passwordWidget(),
        }

RegistrationApp/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import user_registration_form, login_form
from .models import user_registration
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
# Create your views here.
response = {}


def registrationIndex(request):
    if (request.method == "POST"):
        user_form = user_registration_form(request.POST)
        if (user_form.is_valid()):
            response['nama'] = request.POST['nama']
            response['tanggal_lahir'] = request.POST['tanggal_lahir']
            if (user_registration.objects.filter(email=user_form.cleaned_data['email']).exists()):
                messages.error(request, "This email has already existed.")
                return HttpResponseRedirect('/registration/')
            response['email'] = request.POST['email']
            response['password'] = request.POST['password']
            form = user_registration(nama=response['nama'], tanggal_lahir=response['tanggal_lahir'], email=response['email'], password=response['password'])
            user = User.objects.create_superuser(response['nama'], response['email'], response['password'])
            name = response['nama'].split(' ')
            user.first_name = name[0]
            user.last_name = ""
            user.save()
            form.save()
            return HttpResponseRedirect('/program/')
    else:
        user_form = user_registration_form()
    return render(request, 'registration_index.html', {'user_form': user_form})

def loginIndex(request):
    if (request.method == "POST"):
        form = login_form(request.POST)
        if (form.is_valid()):
            response['nama'] = request.POST.get('nama', False)
            response['password'] = request.POST.get('password', False)
            print(response['nama'], response['password'])
            users = authenticate(request, username=response['nama'], password=response['password'])
            if users is not None:
                if users.is_active:
                    login(request, users)
                    return HttpResponseRedirect('/program/')
                else:
                    messages.error(request, "Login Failed.")
            else:
                messages.error(request, "Invalid Username or Password")
            print('masuk2')
    else:
        form = login_form()
    return render(request, 'login_index.html', {'form': form})

RegistrationApp/templates/login_index.html
{% load static %}
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/icon" href="{% static 'image/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Login</title>
  </head>
  <body>

    {% include 'navbar.html' %}

    <div class="yusuf-section-konten" style="height: 60rem; padding-top: 15rem;">
      <div class="yusuf-max-width">
        <div class="align-self-center">
            <h1 class="text-center yusuf-bold">Login</h1>
        </div>
        <div class="yusuf-container-form yusuf-container-konten">
          <form method="POST">
            {% if messages %}
              {% for message in messages %}
                {% if message.tags == "error" %}
                  <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% endif %}
              {% endfor %}
            {% endif %}
            {% csrf_token %}
            {{ form }}
            <div class="yusuf-container-konten text-center">
              <button type="submit" class="btn btn-primary yusuf-isi-button border-0">
                <span class="yusuf-bold">Login</span>
              </button>
            </div>
          </form>
          <hr>
          <button class="btn btn-light" onclick="location.href='{% url 'social:begin' 'google-oauth2' %}'">
                Login dengan Google
          </button>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    {% include 'footer.html' %}
  </body>
</html>

RegistrationApp/templates/registration_index.html
{% load static %}
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/icon" href="{% static 'image/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Donasikan Uangmu !</title>
  </head>
  <body>

    {% include 'navbar.html' %}

    
    <div class="yusuf-section-konten" style="height: 60rem; padding-top: 15rem;">
        <div class="yusuf-max-width">
          <div class="align-self-center">
            <h1 class="text-center yusuf-bold">Registration</h1>
          </div>
          <div class="yusuf-container-form yusuf-container-konten">
            <form method="POST">
              <div id="alert"></div>
              {% csrf_token %}
              {{ user_form }}
              <div class="yusuf-container-konten text-center">
                <button type="submit" id="submit" class="btn btn-primary yusuf-isi-button border-0">
                  <span class="yusuf-bold">SUBMIT</span>
                </button>
              </div>
          </form>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script>
        $('#submit').prop("disabled", true);
    
        $("input").keyup(function () {
            email = $('#id_email').val();
            nama = $('#id_nama').val();
            console.log(email)
            $.ajax({
                method: "POST",
                url: '/validate/',
                data: {
                    'nama': nama,
                    'email': email,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: 'json',
                success: function (data) {
                    if (data.is_taken) {
                        $("#alert").html('<div class="alert alert-danger" role="alert">Email tersebut sudah pernah didaftarkan sebelumnya, silakan daftar dengan email lain !</div>')
                        $('#submit').prop("disabled", true);
                    } else {
                        $(".alert.alert-danger").remove()
                    }
                    if (data.nama_is_taken) {
                        $("#alert").html('<div class="alert alert-danger" role="alert">Nama tersebut sudah pernah didaftarkan sebelumnya, silakan daftar dengan nama lain !</div>')
                        $('#submit').prop("disabled", true);
                    } else {
                        $(".alert.alert-danger").remove()
                    }
                    console.log(true)
                    if (($('#id_nama').val() == '' || $('#id_email').val() == '' || $('#id_jumlah_uang').val() == '') || data.is_taken){
                        $('#submit').prop("disabled", true);
                    } else {
                        $('#submit').removeAttr('disabled');
                    }
                }
            });
        });
        </script>

    {% include 'footer.html' %}
  </body>
</html>